### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode characters

### ISSUE THREAD

**Issue by sdbrown67** [ultmaster/whisper-movie#1]
chardet==5.1.0
charset-normalizer==3.1.0
idna==3.4
-e git+https://github.com/ultmaster/whisper-movie.git@5d05c8075e5159767dbccfc7c7dfa3da243f1027#egg=nni_amlt
pysrt==1.1.2
requests==2.31.0
urllib3==2.0.3

[2023-06-13 19:06:34] (INFO) Using whisper to translate outputs\02700-03300.mp3
[2023-06-13 19:07:01] (INFO) Translation saved: outputs\02700-03300.srt
[2023-06-13 19:07:01] (INFO) Clipping audio file video.mp4 from 3240 to 3840 and saving to outputs\03240-03840.mp3
[2023-06-13 19:07:14] (INFO) Audio segment saved: outputs\03240-03840.mp3
[2023-06-13 19:07:14] (INFO) Using whisper to translate outputs\03240-03840.mp3
[2023-06-13 19:07:14] (INFO) Using whisper to translate outputs\03240-03840.mp3

Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\xampp\htdocs\whisper-movie\whispermovie\translate.py", line 260, in <module>
    main()
  File "C:\xampp\htdocs\whisper-movie\whispermovie\translate.py", line 254, in main
    segment_and_translate(audio_path, main_directory,
  File "C:\xampp\htdocs\whisper-movie\whispermovie\translate.py", line 217, in segment_and_translate    translated_path.write_text(response)
  File "C:\Python310\lib\pathlib.py", line 1155, in write_text
    return f.write(data)
  File "C:\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 5364-5366: character maps to <undefined>

**Comment by sdbrown67** [comment]
chardet==5.1.0
charset-normalizer==3.1.0
idna==3.4
-e git+https://github.com/ultmaster/whisper-movie.git@5d05c8075e5159767dbccfc7c7dfa3da243f1027#egg=nni_amlt
pysrt==1.1.2
requests==2.31.0
urllib3==2.0.3

**Comment by ultmaster** [comment]
Looks like whisper API is returning some character that isn't supported by utf-8.

In my experience, the problem will disappear after retrying. I've just pushed a encoding patch. Pull the latest version if retrying doesn't work.

**Comment by sdbrown67** [comment]
Seems to have fixed that issue, but theres more.
