### ISSUE TITLE
[2023-06-14 19:01:15] (ERROR) Maximum number of retries (0) exceeded.

### ISSUE THREAD

**Issue by sdbrown67** [ultmaster/whisper-movie#2]
[2023-06-14 19:01:15] (ERROR) Maximum number of retries (0) exceeded.
Traceback (most recent call last):
  File "C:\Users\sdbro\.virtualenvs\whisper-movie-CpFPbU1T\lib\site-packages\urllib3-2.0.3-py3.10.egg\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "C:\Users\sdbro\.virtualenvs\whisper-movie-CpFPbU1T\lib\site-packages\urllib3-2.0.3-py3.10.egg\urllib3\connection.py", line 454, in getresponse    
    httplib_response = super().getresponse()
  File "C:\Python310\lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Python310\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Python310\lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "C:\Python310\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Python310\lib\ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\sdbro\.virtualenvs\whisper-movie-CpFPbU1T\lib\site-packages\requests-2.31.0-py3.10.egg\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Users\sdbro\.virtualenvs\whisper-movie-CpFPbU1T\lib\site-packages\urllib3-2.0.3-py3.10.egg\urllib3\connectionpool.py", line 844, in urlopen    
    retries = retries.increment(
  File "C:\Users\sdbro\.virtualenvs\whisper-movie-CpFPbU1T\lib\site-packages\urllib3-2.0.3-py3.10.egg\urllib3\util\retry.py", line 470, in increment      
    raise reraise(type(error), error, _stacktrace)
  File "C:\Users\sdbro\.virtualenvs\whisper-movie-CpFPbU1T\lib\site-packages\urllib3-2.0.3-py3.10.egg\urllib3\util\util.py", line 39, in reraise
    raise value
  File "C:\Users\sdbro\.virtualenvs\whisper-movie-CpFPbU1T\lib\site-packages\urllib3-2.0.3-py3.10.egg\urllib3\connectionpool.py", line 790, in urlopen    
    response = self._make_request(
  File "C:\Users\sdbro\.virtualenvs\whisper-movie-CpFPbU1T\lib\site-packages\urllib3-2.0.3-py3.10.egg\urllib3\connectionpool.py", line 538, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\Users\sdbro\.virtualenvs\whisper-movie-CpFPbU1T\lib\site-packages\urllib3-2.0.3-py3.10.egg\urllib3\connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=60.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\xampp\htdocs\whisper-movie\whispermovie\translate.py", line 260, in <module>
    main()
  File "C:\xampp\htdocs\whisper-movie\whispermovie\translate.py", line 254, in main
    segment_and_translate(audio_path, main_directory,
  File "C:\xampp\htdocs\whisper-movie\whispermovie\translate.py", line 216, in segment_and_translate
    response = translate(f, prompt, timeout=timeout, max_retries=max_retries)
  File "C:\xampp\htdocs\whisper-movie\whispermovie\translate.py", line 40, in translate
    response = requests.post(
  File "C:\Users\sdbro\.virtualenvs\whisper-movie-CpFPbU1T\lib\site-packages\requests-2.31.0-py3.10.egg\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\Users\sdbro\.virtualenvs\whisper-movie-CpFPbU1T\lib\site-packages\requests-2.31.0-py3.10.egg\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\sdbro\.virtualenvs\whisper-movie-CpFPbU1T\lib\site-packages\requests-2.31.0-py3.10.egg\requests\sessions.py", line 589, in request       
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\sdbro\.virtualenvs\whisper-movie-CpFPbU1T\lib\site-packages\requests-2.31.0-py3.10.egg\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\sdbro\.virtualenvs\whisper-movie-CpFPbU1T\lib\site-packages\requests-2.31.0-py3.10.egg\requests\adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=60.0)

**Comment by sdbrown67** [comment]
As an extra note, it might be worth adding  a flag to skip successfully generated mp3/srt files as it can get expensive re-creating successful batches more than once. Maybe keep a log file of successful batches created. so those that didnt finish can be overwritten but those that are okay can be skipped.

**Comment by ultmaster** [comment]
> requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=60.0)

Unstable OpenAI API? Does this reproduce every time or does it happen occasionally? Would you try `--max-retries 5`?

> As an extra note, it might be worth adding a flag to skip successfully generated mp3/srt files as it can get expensive re-creating successful batches more than once.

I think they are already skipped. Via `--reuse` flag.
